spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    username: crud
    password: crud
    url: jdbc:h2:mem:crud
    driverClassName: org.h2.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      use_sql_comments: true
      format_sql: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    validate-on-default: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG